global:
  scrape_interval:     40s # By default, scrape targets every 15 seconds.
  evaluation_interval: 60s # By default, scrape targets every 15 seconds.
  scrape_timeout: 30s
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'kafka'
    scrape_interval: 40s
    static_configs:
     - targets: ['kafka-jmx-exporter:8080']
